openapi: 3.0.3
info:
  title: Traffic Monitoring API
  version: "1.0.0"

paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK

  /ai/analyze:
    post:
      summary: Analyze traffic video
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
      responses:
        "200":
          description: Analysis result